---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
    check:
      jobs:
        - openstack-tox-linters
        - py3-bandit
        - py3-flake8
        - patch-alarm-tox-pylint
        - patch-alarm-tox-py39
        - software-tox-flake8
        - software-tox-pylint
        - software-tox-py39
        - software-client-tox-flake8
        - software-client-tox-pylint
    gate:
      jobs:
        - openstack-tox-linters
        - py3-bandit
        - py3-flake8
        - patch-alarm-tox-pylint
        - patch-alarm-tox-py39
        - software-tox-flake8
        - software-tox-pylint
        - software-client-tox-flake8
        - software-client-tox-pylint
    post:
      jobs:
        - stx-update-upload-git-mirror

- job:
    name: py3-bandit
    parent: tox
    nodeset: debian-bullseye
    vars:
      tox_envlist: bandit

- job:
    name: py3-flake8
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
    vars:
      tox_envlist: flake8


- job:
    name: software-tox-py39
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
    files:
      - software/*
    vars:
      tox_envlist: py39
      tox_extra_args: -c software/tox.ini

- job:
    name: software-tox-flake8
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
    files:
      - software/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c software/tox.ini


- job:
    name: software-tox-pylint
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
    files:
      - software/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c software/tox.ini


- job:
    name: software-client-tox-flake8
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/utilities
    files:
      - software-client/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c software-client/tox.ini


- job:
    name: software-client-tox-pylint
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
    files:
      - software-client/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c software-client/tox.ini
    voting: false


- job:
    name: patch-alarm-tox-pylint
    parent: tox
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
    files:
      - patch-alarm/patch-alarm/*
    vars:
      bindep_profile: pylint
      tox_envlist: pylint
      tox_extra_args: -c patch-alarm/patch-alarm/tox.ini

- job:
    name: patch-alarm-tox-py39
    parent: tox-py39
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
    files:
      - patch-alarm/patch-alarm/*
    vars:
      bindep_profile: python3
      python_version: 3.9
      tox_envlist: py39
      tox_extra_args: -c patch-alarm/patch-alarm/tox.ini

- job:
    name: flock-devstack-update
    parent: flock-devstack-base-min
    required-projects:
      - starlingx/integ
    vars:
      tox_envlist: functional
      devstack_plugins:
        # integ: https://opendev.org/starlingx/integ
        update: https://opendev.org/starlingx/update
- job:
    name: stx-update-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/update to
      github.com/starlingx/update
    vars:
      git_mirror_repository: starlingx/update
    secrets:
      - name: git_mirror_credentials
        secret: stx-update-github-secret3
        pass-to-parent: true

- secret:
    name: stx-update-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - OUgR39pbgKojSlERv8d3Zx77+JRjZk9IpSTZaIHYsZ6kaz8j9Nw6bBkqLT9ZQuBWBmGs+
          D+NXiG96j6t3Kxnxg04LKe6IBtmawzISsFSvjID2Jq1+KvBW0+SwT7i6lAV0c6jOyaEVM
          w4pm6znWER7lsB7f5JPW9yseezXPIV1doVkzu5vty9Nsufa/aLUzp/CSPQsy3iNS5ZxWQ
          0W8h4nrGXIpoNGUS7gxOZV/fvgjNqAsaSaax8zeCWfpPnhjSSgitHDNyJU6cro2Z9sH7O
          /owoPCccORksd+y1HxxeVhvbkGQflG12bAV/2H6r/NZDmeDLklczoyGuz/wo+Z3UIa59U
          nNCSP3xUM5p5ScbCgP0owN7xsO0mR1yrLbCmaAh9kvoMgDZm2wZXn2/Q1+obPJkStnKlf
          wVGrq4NK0VnoXhts3ZExYdKWTZl1ycdF40cay0ceGktJE8gAEvm+SB24Gc3NPFfswdCyY
          OpbGhY9IjCfxo9dZ120gQhKPXv986qCLGxgYe8NaSJhsZYNSJDbwF1ZRj1qkHkzJsGazL
          XVCSG1vOELbfqcYJOKA8s1Gibr5EDWeIOHfcO/q5REf2BJpxOU8Z+VbFoM46GOz7fGjmg
          jM1lbnpIzvLch4ohQLmiQ3ubGdaRVokf/w+Nzeip3H4QSQPyLa/0MrPzFy/Oc4=
        - jC2lGVsDrfyAKdFW/15wOfyK9ETk4Zym2/+wmG/kkPm0vwuDt4oqTgMSJabPFIO2M6bx/
          p4x0GI1vOWv3ueZdJ01cMUVZGgbH2vNc4iaIQNmPcJKOwQPB5Jy2U8VDlzy47q/9qmrml
          cr+SMsWhilo+iB5Uh8sKv0fQdLvyF9p3dCuzHqZhpD32TkGPSYehBl7c5hS91NBrh1zwM
          IFJuwjbgsS7Peptq+Z9aQZp3BbsrZDIhnzKCQvbcrZCQdDDLGJSiXBo5HVP9wnBROwUwC
          KNltjOIL70ZqRQJEmc9E9ayY6FgEaX8AkDJJ+eAEym/hG9xxHUVKNWIF7YUsiGM5akESa
          tYxTjavHxrw8umthGzEN5cxSRM2NqHJmE0Tqu6/EP88QB9aWEHO+bcai1wlK/uvxoJ2Rm
          zxHj6D60Oi0KQLRGO0GE7IFrRv9K7lnyA8vlSUx7zPs1RkCCI/elQkDT64y+in3/umfSv
          PrH2WeAHK/MvtJWqH7tPNTGCf7j2K0Y66sXf7m1/npHMWTb9cG+zQWzXRnZNAcoos/uFl
          wYNDdzp23pEMtkwm0KXjK9vdMqS2j6XAnVoCwUzzhghhYYEHSPpha7VF6/E8hdUrgWpMC
          bDIIqyEYpsEKn2RzNa0lgd/m65/4cdkv71/EdgtBGIaExQtieyCql7T9QdyZ00=
        - DBDz/EwVM043p0zHqid6XeLdYezBVAxRDHPax+xzSNOue3SImFXem9ZwaDMYrVzZLoFO1
          wm/7k9UTZKvAdePYA4lFD7iDCk2IT5Gx7csS7A5f03Kq60SWiq0mZdrKbiQKg6wLisSSs
          4HbxXnEFTwwITmm2tzzkRZNPHWlRJYgp1FERBqyU29j5qxcKoNrT6P/WlW64NOq7YciWP
          3G8+2Bh9420CkSL4m5XM00MJA9C8G1UcY4cGz3DXVg2miVPPuar6Y60aiP3RsXbNj3pK0
          bOoQDtopSRX5x5D3myrNaGrWORcqML+O6NBWLbCyhpQU5iCkTcOeaFkGWoc0VObO+pzLy
          0iNR8NoBE48KhxZCvskv2IR/3cfo8N1xWGpwe23WiiM4n4CZwmocEWK0iN+dIKqn/98dn
          TBTj8RgjEG6HKiCy2B9gwJHj4xQ2tKc18ajrYyJeqpg+/DzqktUw0V6Sz1hE4/br4Qx6y
          SlFbuN3bfMPeWNDdbtbXuRpMhd/Nhp4rMILa3gWxN/L6RNrO7PajiEUbyr8VvkgOpABnu
          Qf8DkLSYrCLvHFX3LCjJ5oJGSE1MLqUuJWQJO5WNwrPudI8P4lh5r8k3R3zFW9usIUZXJ
          6iuLQPyICczNwRX3KJYhVB9yDutwYAqSlDkR2yCkPMXVYZsxckjY5lluCV8SVU=
        - XP4DGcscMl8RFbzTE+cQk5ez7T143/Z3Mza54QMhYhFInCVEbRz67GzsTl+R5ayJnMkGP
          1ZwikiGiRR3Olc3I8z0ay8j2u5ihY7BH7nZbal69125QkWPgkvbmFGvis56VzCQRJ3yjX
          R0vwOxdQ4gDBtZ/KHnaiMZQrvVlqvKCTN8lMGMmHZdwaCf4MwW9opg3vTkIPW9rQr2AAR
          UdqnYnoAZ3vSFRFK+SmclNM3sYb+O1m5wLMa57kNDeYLyAiOuRPbrauz+gKrIafNi6DqU
          XBdcOePBC3xTEpxSb4FnR6K5qoudctKCCRuFAkWhLvKdJW7lHy357XtQ9U0E765+ix1mb
          W8XyBSPIYMQ1IdkWI7qPtMOgJ+mO1tMoxJZwVrGKYWev4B75wOMO2dn+xXGLBbZbCpAil
          sWXFSS5hbHyjhYu5LkWEbQug9IE2kon/1thgDGRvjUMpLrGFP4r72INGC76HI/89Ydzb8
          nf69o4WOh3ppboyN0ESxEBXPs94WwG1uoona+n/mhuuMgQnUZ5n98t7B6sGEjKA9tluG6
          R4cOFtMIjbyjMkTUM8paDFrmaYLATyzOlhwL48EwFPY0zdXlvOMmf+UJx9Ax7p7+LIEoD
          5CBKMb4KIPCaZU6OQ2XV0VPWxfHg1d8Tp6ivNZ7ZrJdTytZpvXCUN/bKYhDQxQ=
        - mhJjfxQTaH0aq6WARZrAmj8bmhJb42zqk8bBLX6WV6x9ojtriVsRX2MAKjagSYnrDCyjG
          tQUQTRCB8qu2eFY1BL9+blXObfhBp1mstBt2VkVYwkow3hzdU13s/RIqw4qGwKOb42Tbq
          yMl2t9KURjriO8iTpuve3nkoaOP9Y/5MJnFkULfLhLru09goMkL8W6Uu9L59KvKLlwfwN
          Asub30JxY4+PfEB+amWtYz4NeLRbT+2yc/BSiyUkVlfyA9xnrwJ2T+n5oMtYju3jrSTp3
          71n7hXnN1EL2SUFIrRKGZUMQ7NkmhcqEoPc/rBTlHqTAiKPP4NzSxCyj6U2eUgsr2/Bum
          iKSXqkMvFxPw2MaxnvkmiQCe3M30xmQRL2GPm3mxiAwNj/gWoeALhD28myGmXWDBOd9Yo
          FNpt898co/TuAYSfZ21bXI6LvW6O0450cq3rfJptxOCqxV2G7Zp2RoaGEHHFD9YzIQjrb
          7lXzoTVUD0svKIIwShx9rfkoN+QtwDMuToFCElDm1ej75OEAxj9cBeVs/8Vt++EzQuf4d
          23nsQNmoWWdsROYbTvfd42mlIk6sNo5fw4zgt3XdZEuWFgnBNlJ8PU+BClTt3COvn1Cfx
          k8HHIcuZaHBwzJgWu1RcHoSFSCafLGzXUmHbC4wIluTaLouiAmQ3np3XThn3/M=
        - J4w8+SNiN1efvWQny7KKfsosBHxgt60lKrFS+jCzoBcyk4K1re1XI7Zrzt278lAl9Cqsw
          XJi038z6iNsbClfY7LCo4yH3Hn2PI7z3DMBJ7DR1+X4zDp/Nd9Mr7lKiI9omyCdlsgxvy
          xxeA5Nrj1QJ4SJWc4L63aqVlj+ohvYBZMxNIzOe981ZTr7ouf943fLlBWvSImrJSYxeP1
          oUlV4uPxYLBPXqUlQrysMc9OIKWMLm40TWHX2fiiweibBbsgDvq/2rcFKmO7jFFz7uOck
          vIxt3hAv4vo2N1Fp7v70BzK2j7tWThaOZaZ9Ga4Rb2TFvC0XnnPIzaI1L7l6NLeWGE+x3
          E8IQXhKXqWoPdJyBdS6WnsCdeEpfVrjzZ2BBkrEyfB0Q3riPcleGJBrd77349CNqj+Z39
          KggJ8Xel6E5PfI3gs4iTUATLbaH3kaOGcNzFxH+aqy+ftmaWrt+cogLkxqh4K2tumDYHs
          znojynIx7YoY5/O1d3P3AYwTsI4XV7H4nsIm3bUba1S6DTv+m1E1omDK4lMQ4J8fl3b5T
          tzyJPwp+U5WIu0zibYevIdXxMQ+FM4AQoEnUqQbT994dCYGN49TwDZAmz4KBh4uLmCsDa
          42iRuDBRCf7DfH5lHqONfsIb+/yafDD+phWGkubwQvEQ6R4dfFPGp9BE4lH/Qw=
        - aoslWQ4TbBhCYNWUYlyD2oENhkOCLqXAhTJwRCvQfAvG4KDGNDcxuf+aXsfC9PfIQT/QA
          9lbMzfN/yvvvbKrGgtRKJnZqJffzHjH+nSMBIcibfbh2+EqYVWou0Pp8PVHF//chjFK32
          +h6+Z8Twd4dBOoW6f7yYE1azIDzwxO0ht8E1+Id4JYL6rX8NX3zlbsDab5krfFll7AWer
          LKDxbtXoBZkDCFbxipzZilNIw0mVrzT/+/YCqC7ikWlAtiCNlLUIZL+mYvwdFqZYrFBqB
          i79rHE1oHi+44loqQxx1j3dsmd3GRhaLBADia4oAt70VzoJxkLD0KGMpAgqELjoeWuBV3
          SSsL70Tr2AnyN4NJT3fAvShwJmvN5oAqMv6myb56ceN3qrRlO5P5GBq/LkaV0EjKCzxk9
          iALQB5jc/CnrSjiBcpmF1yYwNKM1/RYlqBLu889OqgMKmHiSxY0GCrVUkrfMW7x2Jm1Ab
          XmhOj9kjRFw5fanrVsh0oZwXSi013CzW3GT0EuIcb1z4LuAXnZLGVN1THnPEdzfD/pr2Q
          Z6kmXoZDiQe6Fq7PilRP3DVPeg5CsZiurzLgVgYx28fHSRx5Z6LkQ/zbrLWjetVxS7Esq
          2nrupHgCUSZ4Go/AX4kYzlZqBRlpnc8X1MoqcCoF/ZUCc5H8rnG4iBWqyBc4/4=
