#!/bin/bash
#
# Copyright (c) 2023-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

. /etc/software/software-functions

declare REBOOT_STATUS=""

if [ -z "$1" ]
then
    loginfo "No input parameter provided to identify script type."
    exit 0
fi

if [ -n "$2" ]
then
    REBOOT_STATUS="$2"
    loginfo "Reboot status: $2"
fi

declare DIR="${PATCH_SCRIPTDIR}/${1}"
declare SCRIPTS=$(find $DIR -type f -executable | sort -V)

if [ ${#SCRIPTS} -eq 0 ]
then
    loginfo "No patch install script found at the directory ${DIR}"
    exit 0
fi

declare -i NUM_SCRIPTS=$(echo "$SCRIPTS" | wc -l)

loginfo "Running $NUM_SCRIPTS patch install scripts"

declare SCRIPTLOG=/var/log/software.log
cat <<EOF >>$SCRIPTLOG
############################################################
`date "+%FT%T.%3N"`: Running $NUM_SCRIPTS patch install scripts:

$SCRIPTS

############################################################
EOF

declare -i FAILURES=0
for cmd in $SCRIPTS
do
    cat <<EOF >>$SCRIPTLOG
############################################################
`date "+%FT%T.%3N"`: Running $cmd

EOF

    bash -x $cmd "$REBOOT_STATUS" >>$SCRIPTLOG 2>&1
    rc=$?
    if [ $rc -ne $PATCH_STATUS_OK ]
    then
        let -i FAILURES++
    fi
    cat <<EOF >>$SCRIPTLOG
`date "+%FT%T.%3N"`: Completed running $cmd (rc=$rc)
############################################################

EOF
done

cat <<EOF >>$SCRIPTLOG

`date "+%FT%T.%3N"`: Completed running scripts with $FAILURES failures
############################################################
EOF

exit $FAILURES
