#!/bin/bash
# Devstack settings

# This plugin enables StarlingX stx-update services and follows the
# DevStack plugin contract:
# https://docs.openstack.org/devstack/latest/plugins.html#plugin-sh-contract

# Services
# sw-patch

# Defaults
# --------

STX_UPDATE_NAME=update

######### Plugin Specific ##########
enable_service $STX_UPDATE_NAME

# This must not use any variables to work properly in OpenStack's DevStack playbook
define_plugin update
# This works for Zuul jobs using OpenStack's DevStack roles
#plugin_requires update xxxx

# Initial source of lib script
source $DEST/update/devstack/lib/update
