#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/update/patch-alarm)

mkdir ${PKG_BUILD_NAME}

# Copy source files from multiple locations to build root.
cp -pr ${SRC}/patch-alarm/* ${PKG_BUILD_ROOT}
cp -pr ${SRC}/scripts ${PKG_BUILD_ROOT}
